# Generated by Django 2.1.2 on 2018-11-12 12:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StatusTransaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('_id', models.CharField(max_length=255)),
                ('request_id', models.CharField(max_length=255)),
                ('account_id', models.IntegerField()),
                ('account_type', models.CharField(blank=True, default='None', max_length=255, null=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('state', models.IntegerField(blank=True, null=True)),
                ('time', models.CharField(max_length=255)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('error', models.TextField(blank=True, default='None', max_length=255, null=True)),
                ('status', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='PayMe.StatusTransaction')),
            ],
        ),
    ]
